version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12341234
      MYSQL_DATABASE: search_test
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  es_data:
  mysql_data: